# Generated by Django 5.2 on 2025-07-19 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='published_at',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 19, 12, 34, 26, 888226, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
