# Generated by Django 5.2 on 2025-07-25 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_remove_questionmodel_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('dra', 'Draft')], default='dra', max_length=3),
        ),
    ]
